input: lufthansa
model_name: owlvit
output_path: data/results/owlvit/
remove_background: True
preprocessing: []
postprocessing: ['BBoxSizeFilter', 'BBoxOnObjectFilter', 'TopKFilter']
evaluator: 
  threshold: 0.0
  iou_threshold: 0.1